### ISSUE TITLE
Cannot run tests in IntelliJ idea - XemblyLexer and XemblyParser not found

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/xembly#48]
When I try to run some tests in IntelliJ Idea, I can't because 2 classes can't be found - see http://i.imgur.com/nLMyprX.png .

So I have to use Maven to run a test.

Please provide some way to run xembly unit tests directly in Idea.

**Comment by yegor256** [comment]
@dpisarenko I'm having the same problem. That's because these two classes should be generated by ANTLR maven plugin. So, run `mvn clean compile` and then run tests in IntelliJ IDEA. They will work. You should run Maven only once. Files will be generated into `./target` and IDEA will pick them up.

If you really want to teach IDEA to run ANTLR compiler automatically, you should install ANTLR plugin for it. I tried and it didn't work for me.
